---
- name: Install packages [socat] [conntrack] [ipset]
  apt:
    name: ["socat", "conntrack", "ipset"]
    state: latest
    update_cache: yes

- name: Download Kubernetes node binaries
  unarchive:
    src: https://dl.k8s.io/v1.15.0/kubernetes-node-linux-amd64.tar.gz 
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/kubernetes/node/bin/kubelet

- name: Create kubelet service
  copy:
    src: kubelet.service
    dest: /etc/systemd/system/kubelet.service

- name: Create kubelet config file
  template:
    src: kubelet-config.yaml.j2
    dest: /etc/kubernetes/kubelet-config.yaml 
- name: Create /etc/kubernetes/manifests directory
  file:
    path: /etc/kubernetes/manifests
    state: directory
- name: Create kubelet kubeconfig file
  copy:
    src: /tmp/kubernetes/certificates/configs/kubelet/{{ ansible_hostname }}/kubelet.config 
    dest: /etc/kubernetes/manifests/kubelet.conf

- name: Create kube-proxy service
  copy:
    src: kube-proxy.service
    dest: /etc/systemd/system/kube-proxy.service

- name: Create kube-proxy config file
  template:
    src: kube-proxy-config.yaml.j2
    dest: /etc/kubernetes/kube-proxy-config.yaml
- name: Start kubelet and kube-proxy services
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: "{{ item }}"
  with_items:
    - kubelet
    - kube-proxy
