---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: harbor
  name: harbor
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-initdb
  namespace: harbor
data:
  initdb.sql: |
    CREATE DATABASE notary_signer;
    CREATE DATABASE notary_server;
    CREATE DATABASE clair;
    CREATE DATABASE registry;
