---
- hosts: all
  any_errors_fatal: true
  become: true
  roles:
    - connexion-to-hosts
- hosts: deploy
  become: true
  roles:
    - compliance-checks
    - install-kubectl
    - install-go
    - generate-certs
    - gen-encrypt-policy-k8s
    - etcd-gen-init
    - server-k8s-gen-configs
- hosts: etcd
  become: true
  roles:
    - install-go
    - setup-etcd
- hosts: masters
  become: true
  roles:
    - install-go
    - setup-master
    - install-kubectl
    - configure-kubeconfig
- hosts: workers
  become: true
  roles:
  - import-certs
  - install-go
  - install-kubectl
  - install-runtimes
  - setup-worker
  - configure-kubeconfig
- hosts: deploy
  become: true
  roles:
    - install-go
    - install-kubectl
    - configure-kubeconfig
    - post-scripts

