---
cn_root_ca: ilkilabs
c: FR
st: Ile-De-France
l: Paris
expiry: 87600h
advertise_ip_masters: 84.39.47.22

etcd_initial_cluster: master-k8s-3=https://10.20.20.7:2380,master-k8s-2=https://10.20.20.8:2380,master-k8s-1=https://10.20.20.6:2380
