---
- name: Create folders
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - /tmp/kubernetes
    - /tmp/kubernetes/configs
    - /tmp/kubernetes/configs/etcd

- name: Generate folder etcd hosts
  file:
    path: /tmp/kubernetes/configs/etcd/{{item }}
    state: directory
  with_items: "{{ groups['etcd'] }}"

- name: Generate etcd.service
  template:
    src: etcd.service.j2
    dest: /tmp/kubernetes/configs/etcd/{{ item }}/etcd.service
  with_items: "{{ groups['etcd'] }}"
