- name: Check Helm repo bitnami
  command: |
    /usr/local/bin/linux-amd64/helm --kubeconfig \
    {{ data_path }}/certificates/configs/admin/admin.conf \
     repo list
  register: check_helm_repo_bitnami
  changed_when: false

- name: Helm install repo bitnami
  command: |
    /usr/local/bin/linux-amd64/helm --kubeconfig \
    {{ data_path }}/certificates/configs/admin/admin.conf \
    repo add bitnami https://charts.bitnami.com/bitnami
  when: >
    check_helm_repo_bitnami.stdout is not search("bitnami")

- name: Check harbor-redis Release
  command: |
    /usr/local/bin/linux-amd64/helm --kubeconfig \
    {{ data_path }}/certificates/configs/admin/admin.conf \
    list
  register: check_harbor_redis_release
  changed_when: false

- name: Install harbor-redis Release
  command: /usr/local/bin/linux-amd64/helm --kubeconfig \
    {{ data_path }}/certificates/configs/admin/admin.conf \
    install --name harbor-redis --namespace harbor \
    --set master.persistence.enabled=true --set master.persistence.storageClass=rook-ceph-block \
    --set slave.persistence.enabled=true --set slave.persistence.storageClass=rook-ceph-block \
    --set cluster.enabled=true --set cluster.slaveCount=3 \
    stable/redis
  when: >
    check_harbor_redis_release.stdout is not search("harbor-redis")

- name: Wait for Harbor-Redis HA Cluster to be deployed
  command: kubectl --kubeconfig {{ data_path }}/certificates/configs/admin/admin.conf get pod -n harbor harbor-redis-slave-2
  changed_when: false
  register: harbor_redis_cluster
  until: harbor_redis_cluster.stdout.find("1/1") != -1
  retries: 300
  delay: 10
  run_once: true
