---
- name: Create tempdir
  tempfile:
    state: directory
    suffix: harbor
  register: harbor_tempdir
  changed_when: false

- name: Render configuration for HA Redis Cluster
  copy:
    dest: "{{ harbor_tempdir.path }}/harbor.yaml"
    src: "redis-ha-harbor.yaml"
  changed_when: false

- name: Apply HA Redis Cluster
  command: kubectl --kubeconfig {{ data_path }}/certificates/configs/admin/admin.conf apply -f {{ harbor_tempdir.path }}/harbor.yaml
  register: apply_harbor
  changed_when: >
    apply_harbor.stdout is search("created")

- name: Wait for Calico to be deployed
  command: kubectl --kubeconfig {{ data_path }}/certificates/configs/admin/admin.conf get pod redis-cluster-harbor-5 -n harbor
  changed_when: false
  register: redis_ds
  until: redis_ds.stdout.find("1/1") != -1
  retries: 300
  delay: 10
  run_once: true

- name: Initialize Redis Cluster master/slaves
  expect:
    command: kubectl --kubeconfig {{ data_path }}/certificates/configs/admin/admin.conf exec -it redis-cluster-harbor-0 -n harbor -- redis-cli --cluster create --cluster-replicas 1 $(kubectl get pods -l app=redis-cluster-harbor -o jsonpath='{range.items[*]}{.status.podIP}:6379 ')
    responses:
      Question:
        - yes

- name: Cleanup tempdir
  file:
    state: absent
    path: "{{ harbor_tempdir.path }}"
  changed_when: false
