---
- name: Generate folder
  file:
    path: /tmp/kubernetes/configs/kube-apiserver/{{item}}
    state: directory
    recurse: true
  with_items: "{{ groups['masters'] }}"
- name: generate kube-apiserver.service files
  template:
    src: kube-apiserver.service.j2 
    dest: /tmp/kubernetes/configs/kube-apiserver/{{item}}/kube-apiserver.service
  with_items: "{{ groups['masters'] }}"
