---
pki_path: "{{ data_path }}/pki"
number_workers: "{{ groups['workers'] | length }}"
replicas_openebs: "{{ number_workers if number_workers < '3' else '3' }}"
#replicas_openebs: "{{ groups['workers'] | length }}"
