---
- name: Add Docker repository for {{ ansible_distribution }}
  include_tasks: "repo-{{ ansible_distribution }}.yaml"

- name: Install Docker for {{ ansible_distribution }}
  include_tasks: "docker-{{ ansible_distribution }}.yaml"

- name: Start Runtime
  systemd:
    state: started
    name: docker

- name: Make sure /etc/docker existe
  file:
    path: /etc/docker
    state: directory

- name: Configure /etc/docker/daemon.json
  copy:
    dest: /etc/docker/daemon.json
    src: daemon-{{ ansible_distribution }}.json
  notify:
    - Reload docker

- name: Create /etc/systemd/system/docker.service.d directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    recurse: yes

- name: Make sure docker is running
  systemd:
    state: started
    name: docker
    enabled: yes
