---
- name: Install prerequis packages
  apt:
    name: ['apt-transport-https','ca-certificates','curl','software-properties-common']
    state: latest
    update_cache: yes
- name: Add Docker official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker Repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
- name: Install docker
  apt:
    name: docker-ce=18.06.2~ce~3-0~ubuntu
    state: present
    update_cache: yes
- name: Configure /etc/docker/daemon.json
  blockinfile:
    path: /etc/docker/daemon.json
    create: yes
    marker: ''
    marker_begin: ''
    marker_end: ''
    block: |
      {
        "exec-opts": ["native.cgroupdriver=systemd"],
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m"
        },
        "storage-driver": "overlay2"
      }
  notify:
    - Reload docker
- name: create /etc/systemd/system/docker.service.d directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    recurse: yes
- name: Make sure docker is running
  systemd:
    state: started
    name: docker
