---
- name: "Install {{ item }}"
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add repository
  yum_repository:
    name: docker-ce
    description: Docker YUM repo
    baseurl: https://download.docker.com/linux/{{ ansible_distribution | lower }}/docker-ce.repo
