---
- name: Deploy Flannel Pods
  shell: 'kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.11.0/Documentation/kube-flannel.yml  && touch /var/agorakube/flags/flannel'
  args:
    creates: /var/agorakube/flags/flannel
