---
- name: Label Workers nodes as workers
  shell: "kubectl label node {{item}}  node-role.kubernetes.io/worker=  && touch {{ data_path }}/flags/label-{{item}}"
  args:
    creates: "{{ data_path }}/flags/label-{{item}}"
  with_items: "{{ groups['workers'] }}"
