---
- name: Download Linkerd CLI
  get_url:
    url: "https://github.com/linkerd/linkerd2/releases/download/{{ linkerd_release }}/linkerd2-cli-{{ linkerd_release }}-linux"
    dest: /usr/local/bin/linkerd
    mode: '0751'

- name: Get Linkerd Installation
  command: 'kubectl --kubeconfig {{ data_path }}/certificates/configs/admin/admin.conf get namespaces'
  register: linkerd_is_installed
  changed_when: false

- name: Apply templates
  shell: |
    set -o pipefail
    linkerd --kubeconfig {{ data_path }}/certificates/configs/admin/admin.conf install \
    | kubectl --kubeconfig {{ data_path }}/certificates/configs/admin/admin.conf apply -f -
  register: apply_linkerd
  changed_when: >
    apply_linkerd.stdout is search("created")
    or apply_linkerd.stdout is search("configured")
  when: "'linkerd' not in linkerd_is_installed.stdout"
  args:
    executable: /bin/bash
  environment:
    PATH: /usr/local/bin:{{ ansible_env.PATH }}

- name: Verify if linkerd has successfully started
  command: kubectl --kubeconfig {{ data_path }}/certificates/configs/admin/admin.conf get deploy linkerd-controller -n linkerd
  changed_when: false
  register: linkerd_deployment
  until: linkerd_deployment.stdout.find("1/1") != -1
  retries: 300
  delay: 10
  run_once: true
