---
- name: Include Tasks Flannel
  include_tasks: flannel.yaml
  when: network-cni-plugin == 'flannel'
- name: Include label workers
  include_tasks: label-workers.yaml
  when: label_workers
- name: Deploy CoreDNS to K8S
  include_tasks: coredns.yaml
  when: dns_server_soft == 'coredns'
