---
- name: Configure Traefik Deployment
  copy:
    src: traefik.yaml
    dest: "{{ data_path }}/traefik.yaml"
- name: Deploy Traefik
  shell: kubectl create -f "{{ data_path }}/traefik.yaml" && touch "{{ data_path }}/flags/traefik"
  args:
    creates: "{{ data_path }}/flags/traefik"
