---
- name: Configure Traefik Deployment
  copy:
    src: traefik.yaml
    dest: /tmp/kubernetes/traefik.yaml
- name: Deploy Traefik
  shell: kubectl create -f /tmp/kubernetes/traefik.yaml && touch /tmp/kubernetes/flags/traefik
  args:
    creates: /tmp/kubernetes/flags/traefik
