---
- name: Create /etc/kubernetes/manifests/
  file:
    path: /etc/kubernetes/manifests/
    state: directory
- name: Download Kubernetes server binaries
  unarchive:
    src: https://dl.k8s.io/{{kubernetes_release}}/kubernetes-server-linux-amd64.tar.gz 
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/kubernetes/server/bin/kube-apiserver
- name: Create /var/lib/kubernetes
  file:
    path: /var/lib/kubernetes
    state: directory
- name: Create /etc/kubernetes/config
  file:
    path: /etc/kubernetes/config
    state: directory
- name: Inject kube-encrypt config
  copy:
    src: /tmp/kubernetes/yaml/encryption-provider-config.yaml
    dest: /var/lib/kubernetes/encryption-provider-config.yaml

- name: Import kube-apiserver.service
  copy:
    src: /tmp/kubernetes/configs/kube-apiserver/{{ansible_hostname}}/kube-apiserver.service
    dest: /etc/systemd/system/kube-apiserver.service

- name: Import controller-manager.conf kubeconfig
  copy:
    src: /tmp/kubernetes/certificates/configs/controller-manager/controller-manager.conf
    dest: /etc/kubernetes/manifests/kube-controller-manager.yaml

- name: Import kube-controller-manager.service
  template:
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service

- name: Import kube scheduler yaml file config
  copy:
    src: kube-scheduler.yaml
    dest: /etc/kubernetes/config/kube-scheduler.yaml

- name: Import /etc/kubernetes/manifests/kube-scheduler.yaml
  copy:
    src: /tmp/kubernetes/certificates/configs/scheduler/scheduler.conf
    dest: /etc/kubernetes/manifests/kube-scheduler.yaml

- name: Import service unit kube-scheduler
  copy:
    src: kube-scheduler.service
    dest: /etc/systemd/system/kube-scheduler.service

- name: Load [kube-apiserver] [kube-controller-manager] [kube-scheduler]
  systemd:
    state: started
    daemon_reload: yes
    enabled: yes
    name: "{{ item }}"
  with_items:
    - kube-apiserver
    - kube-controller-manager
    - kube-scheduler

- name: Configure /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
    create: yes
  with_items:  "{{ groups['workers'] }}"
  when: populate_etc_hosts
